version: '3'

networks:
   mongonet:
       external: true
       name: 'mongo-network'
   redisnet:
       external: true
       name: 'redisnet'
   apinet:
       external: true
       name: 'apinet'
   

services:
  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongo-db:27017
      - REDIS_URI=redis://redis  
      - ENABLE_WRITING_HANDLERS=false
    depends_on:
      - mongo-db
      - redis
    networks:
       - redisnet
       - apinet

  mongo-db:
    image: mongo:8.0-rc
    container_name: mongo-db
    environment:
      - NODE_ENV=development
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
       - mongonet
       - apinet
    volumes:
      - ./seed:/data/db

  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    container_name: express
    restart: always
    environment:
      - NODE_ENV=development
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo-db
    ports:
      - 8080:8081  
    networks:
      - mongonet
    depends_on:
      - mongo-db

  redis:
    image: redis:alpine
    container_name: redis
    networks:
       - redisnet
